export const ADD_COCKTAIL = 'ADD_COCKTAIL'; 

export const GET_COCKTAILS = 'GET_COCKTAILS'; 
export const GET_COCKTAIL_SUCCESS = 'GET_COCKTAIL_SUCCESS';
export const GET_COCKTAIL_FAILURE = 'GET_COCKTAIL_FAILURE';

export const SEARCH_COCKTAILS = 'SEARCH_COCKTAILS'; 
export const GET_RANDOM_COCKTAILS = 'GET_RANDOM_COCKTAILS'; 

