export const ADD_COCKTAIL = 'ADD_COCKTAIL'; 

export const GET_COCKTAILS = 'GET_COCKTAILS'; 
export const GET_COCKTAIL_SUCCESS = 'GET_COCKTAIL_SUCCESS';
export const GET_COCKTAIL_FAILURE = 'GET_COCKTAIL_FAILURE';

export const SEARCH_COCKTAILS = 'SEARCH_COCKTAILS'; 
export const SEARCH_COCKTAILS_SUCCESS = 'SEARCH_COCKTAILS_SUCCESS'; 
export const SEARCH_COCKTAILS_FAILURE = 'SEARCH_COCKTAILS_FAILURE'; 


export const GET_RANDOM_COCKTAIL_ITEM = 'GET_RANDOM_COCKTAIL_ITEM'; 
export const GET_RANDOM_COCKTAIL_ITEM_SUCCESS = 'GET_RANDOM_COCKTAIL_ITEM_SUCCESS'; 
export const GET_RANDOM_COCKTAIL_ITEM_FAILURE = 'GET_RANDOM_COCKTAIL_ITEM_FAILURE';


export const GET_DRINK_DETAIL = 'GET_DRINK_DETAIL'; 
export const GET_DRINK_DETAIL_SUCCESS = 'GET_DRINK_DETAIL_SUCCESS'; 
export const GET_DRINK_DETAIL_FAILURE = 'GET_DRINK_DETAIL_FAILURE'; 

export const GET_POPULAR_DRINKS = 'GET_POPULAR_DRINKS'; 
export const GET_POPULAR_DRINKS_SUCCESS = 'GET_POPULAR_DRINKS_SUCCESS';
export const GET_POPULAR_DRINKS_FAILURE = 'GET_POPULAR_DRINKS_FAILURE';
